---
title: "Laurits"
output: html_document
---

```{r}
library(rethinking)
data(Howell1)
d <- Howell1
d$age <- (d$age - mean(d$age))/sd(d$age)
set.seed( 1000 )
i <- sample(1:nrow(d),size=nrow(d)/2)
d1 <- d[ i , ]
d2 <- d[ -i , ]


```

```{r}
m1 <- rethinking::map(
    alist(
        height ~ dnorm( mu , sigma ) ,
        mu <- a + b*age,
        a ~ dnorm(130, 50),
        b ~ dnorm(0, 10),
        sigma ~ dnorm(0, 10)
), data = d1)

m2 <- rethinking::map(
    alist(
        height ~ dnorm( mu , sigma ) ,
        mu <- a + b1*age + b2*age*age,
        a ~ dnorm(130, 50),
        b1 ~ dnorm(0, 10),
        b2 ~ dnorm(0, 10),
        sigma ~ dnorm(0, 10)
), data = d1)

m3 <- rethinking::map(
    alist(
        height ~ dnorm( mu , sigma ) ,
        mu <- a + b1*age + b2*age^2 + b3*age^3,
        a ~ dnorm(130, 50),
        b1 ~ dnorm(0, 10),
        b2 ~ dnorm(0, 10),
        b3 ~ dnorm(0, 10),
        sigma ~ dnorm(0, 10)
), data = d1)

m4 <- rethinking::map(
    alist(
        height ~ dnorm( mu , sigma ) ,
        mu <- a + b1*age + b2*age^2 + b3*age^3 + b4*age^4,
        a ~ dnorm(130, 50),
        b1 ~ dnorm(0, 10),
        b2 ~ dnorm(0, 10),
        b3 ~ dnorm(0, 10),
        b4 ~ dnorm(0, 10),
        sigma ~ dnorm(0, 10)
), data = d1)

m5 <- rethinking::map(
    alist(
        height ~ dnorm( mu , sigma ) ,
        mu <- a + b1*age + b2*age^2 + b3*age^3 + b4*age^4 + b5*age^5,
        a ~ dnorm(130, 50),
        b1 ~ dnorm(0, 10),
        b2 ~ dnorm(0, 10),
        b3 ~ dnorm(0, 10),
        b4 ~ dnorm(0, 10),
        b5 ~ dnorm(0, 10),
        sigma ~ dnorm(0, 10)
), data = d1)

m6 <- rethinking::map(
    alist(
        height ~ dnorm( mu , sigma ) ,
        mu <- a + b1*age + b2*age^2 + b3*age^3 + b4*age^4 + b5*age^5 + b6*age^6,
        a ~ dnorm(130, 50),
        b1 ~ dnorm(0, 10),
        b2 ~ dnorm(0, 10),
        b3 ~ dnorm(0, 10),
        b4 ~ dnorm(0, 10),
        b5 ~ dnorm(0, 10),
        b6 ~ dnorm(0, 10),
        sigma ~ dnorm(0, 10)
), data = d1)


```


```{r}
compare(m1,m2,m3,m4,m5,m6)
```

```{r}




```











